name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # mainブランチにpushされたときに実行

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: docker-test
  IMAGE_TAG: 0.2.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # イメージをプッシュする権限をGITHUB_TOKENに付与
    permissions:
      contents: read
      packages: write

    steps:
      # GitHubリポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # ghcr.ioにログイン
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          usernsme: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Dockerイメージのビルド
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Dockerイメージをビルドしてghcr.ioにプッシュ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # イメージタグとリポジトリ名を指定
          tags: ${{ env.REGISTRY }}/hirotnk1118/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # キャッシュをクリア（オプション、サイズ削減のため）
      - name: Clean up Docker cache
        run: docker builder prune -f
