name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # mainブランチにpushされたときに実行
  workflow_dispatch:  # 手動のActionsトリガー

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: docker-test
  IMAGE_TAG: 0.3.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # イメージをプッシュする権限をGITHUB_TOKENに付与
    permissions:
      contents: read  # コードを読み取る権限
      packages: write  # ghcr.ioにパッケージをpushする権限

    steps:
      # GitHubリポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # ghcr.ioにログイン
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Docker Buildxのセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true  # Buildxをインストール

      # メタデータを生成（latestタグを追加）
      - name: Extract metadata for Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/hirotnk1118/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.IMAGE_TAG }}  # ブランチベースのタグ
            type=ref,event=branch,branch=main,pattern=latest  # mainブランチにpushされた場合にlatestタグを付与

      # Dockerイメージをビルドしてghcr.ioにプッシュ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # 対応するアーキテクチャを指定
          platforms: linux/amd64,linux/arm64
          # イメージタグを指定
          tags: ${{ steps.meta.outputs.tags }}
          # キャッシュの利用
          cache-from: type=gha
          cache-to: type=gha, mode=max

      # キャッシュをクリア（オプション、サイズ削減のため）
      # - name: Clean up Docker cache
      #   run: docker builder prune -f
